apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: xyz-service
  namespace: '851718758933'
  labels:
    serving.knative.dev/route: tardsquad-discord-bot
    serving.knative.dev/configuration: tardsquad-discord-bot
    serving.knative.dev/configurationGeneration: '10'
    serving.knative.dev/service: tardsquad-discord-bot
    serving.knative.dev/serviceUid: bc86c85a-18f2-4245-8be5-7591c32c2a1b
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: erik.westrup@gmail.com
    autoscaling.knative.dev/minScale: '1'
    run.googleapis.com/execution-environment: gen1
    autoscaling.knative.dev/maxScale: '1'
    run.googleapis.com/cpu-throttling: 'false'
spec:
  serviceAccountName: 851718758933-compute@developer.gserviceaccount.com
  containers:
  - image: gcr.io/tardsquad-discord-bot/tardsquad-discord-bot:latest
    env:
    - name: DISCORD_TOKEN
      valueFrom:
        secretKeyRef:
          key: latest
          name: DISCORD_TOKEN
