apiVersion: serving.knative.dev/v1
kind: Revision
metadata:
  name: tardsquad-discord-bot
  namespace: '851718758933'
  labels:
    serving.knative.dev/route: tardsquad-discord-bot
    serving.knative.dev/configuration: tardsquad-discord-bot
    serving.knative.dev/configurationGeneration: '10'
    serving.knative.dev/service: tardsquad-discord-bot
    serving.knative.dev/serviceUid: bc86c85a-18f2-4245-8be5-7591c32c2a1b
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: erik.westrup@gmail.com
    autoscaling.knative.dev/minScale: '1'
    run.googleapis.com/execution-environment: gen1
    autoscaling.knative.dev/maxScale: '1'
    run.googleapis.com/cpu-throttling: 'false'
  ownerReferences:
  - kind: Configuration
    name: tardsquad-discord-bot
    uid: 45574e89-a818-4082-9475-85721b10bcfc
    apiVersion: serving.knative.dev/v1
    controller: true
    blockOwnerDeletion: true
spec:
  containerConcurrency: 1
  timeoutSeconds: 300
  serviceAccountName: 851718758933-compute@developer.gserviceaccount.com
  containers:
  - image: gcr.io/tardsquad-discord-bot/tardsquad-discord-bot:latest
    ports:
    - name: http1
      containerPort: 8080
    env:
    - name: DISCORD_TOKEN
      valueFrom:
        secretKeyRef:
          key: latest
          name: DISCORD_TOKEN
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
