# TODO move to .gcloud or such?
# Reference: https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run
steps:
# Build the container image
- id: tardsquad-discord-bot-build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/tardsquad-discord-bot/tardsquad-discord-bot', '.']
# Push the container image to Container Registry
- id: tardsquad-discord-bot-push
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/tardsquad-discord-bot/tardsquad-discord-bot']
# Deploy container image to Cloud Run
- id: tardsquad-discord-bot-deploy
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'tardsquad-discord-bot', '--image', 'gcr.io/tardsquad-discord-bot/tardsquad-discord-bot', '--region', 'us-central1']
images:
- gcr.io/tardsquad-discord-bot/tardsquad-discord-bot
