# Backup from UI: https://console.cloud.google.com/run/detail/us-central1/tardsquad-discord-bot/revisions?project=tardsquad-discord-bot
# Used by .github/workflows/push_to_gcr.yml for deploying a new revision of the Cloud Run service.
apiVersion: serving.knative.dev/v1
kind: Revision
metadata:
  name: tardsquad-discord-bot-00017-pag
  namespace: '851718758933'
  selfLink: /apis/serving.knative.dev/v1/namespaces/851718758933/revisions/tardsquad-discord-bot-00017-pag
  uid: 5a0a39fe-6406-4ac6-bb2c-628e0544fd82
  resourceVersion: AAXTd98JViM
  generation: 1
  creationTimestamp: '2021-12-19T04:04:14.493771Z'
  labels:
    serving.knative.dev/route: tardsquad-discord-bot
    serving.knative.dev/configuration: tardsquad-discord-bot
    managed-by: gcp-cloud-build-deploy-cloud-run
    gcb-trigger-id: ee3cb5a0-0919-4af2-b2c7-e10bf2c7738d
    serving.knative.dev/configurationGeneration: '16'
    commit-sha: 14bb633580e4d309e9634bab7570da9890696b89
    gcb-build-id: 2d16ec94-8e2e-466d-b180-2af38d701f9e
    serving.knative.dev/service: tardsquad-discord-bot
    serving.knative.dev/serviceUid: bc86c85a-18f2-4245-8be5-7591c32c2a1b
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/client-name: gcloud
    serving.knative.dev/creator: 851718758933@cloudbuild.gserviceaccount.com
    client.knative.dev/user-image: gcr.io/tardsquad-discord-bot/tardsquad-discord-bot
    run.googleapis.com/client-version: 367.0.0
    autoscaling.knative.dev/minScale: '1'
    run.googleapis.com/execution-environment: gen1
    autoscaling.knative.dev/maxScale: '1'
    run.googleapis.com/cpu-throttling: 'false'
  ownerReferences:
  - kind: Configuration
    name: tardsquad-discord-bot
    uid: 45574e89-a818-4082-9475-85721b10bcfc
    apiVersion: serving.knative.dev/v1
    controller: true
    blockOwnerDeletion: true
spec:
  containerConcurrency: 1
  timeoutSeconds: 300
  serviceAccountName: 851718758933-compute@developer.gserviceaccount.com
  containers:
  - image: gcr.io/tardsquad-discord-bot/tardsquad-discord-bot
    ports:
    - name: http1
      containerPort: 8080
    env:
    - name: DISCORD_TOKEN
      valueFrom:
        secretKeyRef:
          key: latest
          name: DISCORD_TOKEN
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
status:
  observedGeneration: 1
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2021-12-19T04:04:33.745698Z'
  - type: Active
    status: 'True'
    lastTransitionTime: '2021-12-19T04:04:40.060051Z'
    severity: Info
  - type: ContainerHealthy
    status: 'True'
    lastTransitionTime: '2021-12-19T04:04:31.989559Z'
  - type: MinInstancesProvisioned
    status: 'True'
    lastTransitionTime: '2021-12-19T04:04:33.745698Z'
    severity: Info
  - type: ResourcesAvailable
    status: 'True'
    lastTransitionTime: '2021-12-19T04:04:25.995613Z'
  - type: Retry
    status: 'True'
    reason: PostponedRetry
    message: System will retry after 0:09:58 from lastTransitionTime for attempt 0.
    lastTransitionTime: '2021-12-19T04:04:33.825921Z'
    severity: Info
  logUrl: https://console.cloud.google.com/logs/viewer?project=tardsquad-discord-bot&resource=cloud_run_revision/service_name/tardsquad-discord-bot/revision_name/tardsquad-discord-bot-00017-pag&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22tardsquad-discord-bot%22%0Aresource.labels.revision_name%3D%22tardsquad-discord-bot-00017-pag%22
  imageDigest: gcr.io/tardsquad-discord-bot/tardsquad-discord-bot@sha256:b841b1042fe2f076212bfea5e08188bdc9257152c2d8a5bfa02956e320ca82e3
